spring:
  datasource:
    # 数据库1配置
    primary:
      jdbc-url: jdbc:mysql://rm-2zeusjfev51pejx51qogd.mysql.rds.aliyuncs.com:3306/xiaodianjia
      username: gdaliroot
      password: Xiaodianjia1122
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: "SELECT 1"
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000 # 30秒
        idle-timeout: 600000 # 10分钟
        max-lifetime: 1800000 # 30分钟
        pool-name: HikariPool-1
        metrics-enabled: true
        health-check-properties:
          enabled: true

    # 数据库2配置
    secondary:
      jdbc-url: jdbc:mysql://rm-2ze1xio717ak28796do.mysql.rds.aliyuncs.com:3306/meijia_com
      username: meijia_online
      password: Bj-Mj-20250115
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: "SELECT 1"
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000 # 30秒
        idle-timeout: 600000 # 10分钟
        max-lifetime: 1800000 # 30分钟
        pool-name: HikariPool-1
        metrics-enabled: true
        health-check-properties:
          enabled: true


    # 数据库3配置
    tertiary:
      jdbc-url: jdbc:mysql://gd.tetuijiudian.cn:3306/gaode66
      username: gaode22
      password: Redbull2266_
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        connection-test-query: "SELECT 1"
        maximum-pool-size: 10
        minimum-idle: 5
        connection-timeout: 30000 # 30秒
        idle-timeout: 600000 # 10分钟
        max-lifetime: 1800000 # 30分钟
        pool-name: HikariPool-1
        metrics-enabled: true
        health-check-properties:
          enabled: true

  # Mybatis Plus 配置
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 使用 SLF4J 实现
    global-config:
      db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0
logging:
  # 设置全局日志级别
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourcompany: TRACE

  # 设置日志输出格式（控制台）
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

  # 设置日志文件输出路径、大小、保留历史文件数等
  file:
    name: 'logs/app.log'
  logback:
    rolling-policy:
      file-name-pattern: 'logs/app-%d{yyyy-MM-dd}.log'
      max-file-size: 10MB # 文件最大为10MB
      max-history: 30 # 保留30天的历史日志
